# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('coper', models.IntegerField(default=0)),
                ('platinum', models.IntegerField(default=0)),
                ('EP', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Toto', max_length=32)),
                ('player_name', models.CharField(blank=True, max_length=32)),
                ('level', models.IntegerField(default=0)),
                ('total_hp', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField(default=0)),
                ('temporary_hp_modifier', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=0)),
                ('char_class', models.CharField(default='hobbo', max_length=256)),
                ('background', models.CharField(default='JustinB', max_length=256)),
                ('alignment', models.CharField(default='Justified', max_length=256)),
                ('speed', models.IntegerField(default=-1)),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('inteligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('presonality_trait', models.TextField(blank=True)),
                ('ideals', models.TextField(blank=True)),
                ('bonds', models.TextField(blank=True)),
                ('flaws', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='rainbow fart', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bisexual', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='plastic duck', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Feature'),
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Trait'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Weapon'),
        ),
        migrations.AddField(
            model_name='bagpack',
            name='character_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Character'),
        ),
    ]
